controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

gift_details:
    path: '/gift/details/{id}'
    controller: App\Controller\GiftsController::details

avis:
    path: '/avis'
    controller: 'App\Controller\AvisController::index'

liste_ajouter:
    path: '/maliste/ajouter/{id}'
    controller: 'App\Controller\listController::add'

liste_voir:
    path: '/maliste/voir'
    controller: 'App\Controller\listController::voirListe'
    methods: ['GET']

liste_retirer:
    path: '/maliste/retirer/{id}'
    controller: 'App\Controller\listController::retirer'
    methods: ['GET']

