controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

gift_details:
    path: '/gift/details/{id}'
    controller: App\Controller\GiftsController::details

avis:
    path: '/avis'
    controller: 'App\Controller\AvisController::index'

